### ISSUE TITLE
Debian 12 support

### ISSUE THREAD

**Issue by legatoj** [idiv-biodiversity/ansible-role-lmod#19]
Can support  for Debian 12 be added?

Also perhaps I am misreading it but  why are  their debian-18 and debian-20 var files:
roles/idiv-biodiversity.lmod/vars/debian-18.yml
roles/idiv-biodiversity.lmod/vars/debian-20.yml

No version of Debian exists with a version number of 18 or 20.

**Comment by wookietreiber** [comment]
I have started updating my roles with molecule tests. I'll take a crack at this role in the next few weeks. I don't know what will happen to the Debian support during that process. I can't make any promises, because we're not using Debian on site.

**Comment by wookietreiber** [comment]
@legatoj I have published v3.0.0 yesterday, including the support for Debian 12/bookworm, tested with molecule. Unfortunately, I can't currently publish to galaxy, you can use the release from GitHub though:

```yml
  - name: idiv_biodiversity.lmod
    src: https://github.com/idiv-biodiversity/ansible-role-lmod
    version: v3.0.0
```

I'm gonna close with that, feel free to reopen if it's not working on your end.
